use_frameworks!

platform :ios, '10.0'

target 'MKGatewayMeteringTwo_Example' do
  pod 'MKGatewayMeteringTwo', :path => '../'

  target 'MKGatewayMeteringTwo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
